import type { LoaderVariants } from "./loader.style";
import { loaderVariants } from "./loader.style";

interface LoaderProps
    extends React.HTMLAttributes<SVGSVGElement>,
        LoaderVariants {
    ref?: React.Ref<SVGSVGElement>;
}

export function Loader({ size, ref, className, ...props }: LoaderProps) {
    const slots = loaderVariants({ size, className });

    return (
        <svg
            xmlns="http://www.w3.org/2000/svg"
            width="1em"
            height="1em"
            viewBox="0 0 18 18"
            fill="none"
            aria-label="loading"
            className={slots.root({ className })}
            ref={ref}
            {...props}
        >
            <title>Loading</title>

            <circle
                opacity="0.15"
                cx="5"
                cy="1"
                r="1"
                fill="currentColor"
                className={slots.wave4()}
            />
            <circle
                opacity="0.15"
                cx="9"
                cy="1"
                r="1"
                fill="currentColor"
                className={slots.wave3()}
            />
            <circle
                opacity="0.15"
                cx="13"
                cy="1"
                r="1"
                fill="currentColor"
                className={slots.wave4()}
            />
            <circle
                opacity="0.15"
                cx="1"
                cy="5"
                r="1"
                fill="currentColor"
                className={slots.wave4()}
            />
            <circle
                opacity="0.15"
                cx="5"
                cy="5"
                r="1"
                fill="currentColor"
                className={slots.wave3()}
            />
            <circle
                opacity="0.15"
                cx="9"
                cy="5"
                r="1"
                fill="currentColor"
                className={slots.wave2()}
            />
            <circle
                opacity="0.15"
                cx="13"
                cy="5"
                r="1"
                fill="currentColor"
                className={slots.wave3()}
            />
            <circle
                opacity="0.15"
                cx="17"
                cy="5"
                r="1"
                fill="currentColor"
                className={slots.wave4()}
            />
            <circle
                opacity="0.15"
                cx="1"
                cy="9"
                r="1"
                fill="currentColor"
                className={slots.wave3()}
            />
            <circle
                opacity="0.15"
                cx="5"
                cy="9"
                r="1"
                fill="currentColor"
                className={slots.wave2()}
            />
            <circle
                opacity="0.15"
                cx="9"
                cy="9"
                r="1"
                fill="currentColor"
                className={slots.wave1()}
            />
            <circle
                opacity="0.15"
                cx="13"
                cy="9"
                r="1"
                fill="currentColor"
                className={slots.wave2()}
            />
            <circle
                opacity="0.15"
                cx="17"
                cy="9"
                r="1"
                fill="currentColor"
                className={slots.wave3()}
            />
            <circle
                opacity="0.15"
                cx="1"
                cy="13"
                r="1"
                fill="currentColor"
                className={slots.wave4()}
            />
            <circle
                opacity="0.15"
                cx="5"
                cy="13"
                r="1"
                fill="currentColor"
                className={slots.wave3()}
            />
            <circle
                opacity="0.15"
                cx="9"
                cy="13"
                r="1"
                fill="currentColor"
                className={slots.wave2()}
            />
            <circle
                opacity="0.15"
                cx="13"
                cy="13"
                r="1"
                fill="currentColor"
                className={slots.wave3()}
            />
            <circle
                opacity="0.15"
                cx="17"
                cy="13"
                r="1"
                fill="currentColor"
                className={slots.wave4()}
            />
            <circle
                opacity="0.15"
                cx="5"
                cy="17"
                r="1"
                fill="currentColor"
                className={slots.wave4()}
            />
            <circle
                opacity="0.15"
                cx="9"
                cy="17"
                r="1"
                fill="currentColor"
                className={slots.wave3()}
            />
            <circle
                opacity="0.15"
                cx="13"
                cy="17"
                r="1"
                fill="currentColor"
                className={slots.wave4()}
            />
        </svg>
    );
}

Loader.displayName = "Ogar-UI.Loader";
